### ISSUE TITLE
Extencion de archivo

### ISSUE THREAD

**Issue by MtiEdgar** [AlmaDelia123/TiendaSombrereria#1]
Favor de checar que sea correcta la extensión de archivo **sitemap**

**Comment by AlmaDelia123** [comment]
si ing me dio error a la hora de subirlo y me indico que checara la
extensión de ese archivo.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
